#!/bin/bash
# Host Setup Script for Agent Sandbox
# Creates isolated 'yolo' user and configures firewall rules
#
# Run with: sudo ./setup-host.sh

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Configuration
SANDBOX_USER="${SANDBOX_USER:-yolo}"
SUBUID_START="${SUBUID_START:-200000}"
SUBUID_COUNT="${SUBUID_COUNT:-65536}"

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root (use sudo)"
    exit 1
fi

echo "=============================================="
echo "Agent Sandbox Host Setup"
echo "=============================================="
echo ""
echo "This script will:"
echo "  1. Create '${SANDBOX_USER}' user for isolated container execution"
echo "  2. Configure subuid/subgid for rootless podman"
echo "  3. Enable lingering for user services"
echo "  4. Add firewall rules to block RFC1918 subnets"
echo ""
read -p "Continue? [y/N] " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 0
fi

echo ""

# =============================================================================
# Step 1: Create user
# =============================================================================

if id "$SANDBOX_USER" &>/dev/null; then
    log_warn "User '$SANDBOX_USER' already exists, skipping creation"
else
    log_info "Creating user '$SANDBOX_USER'..."
    useradd -r -m -s /usr/sbin/nologin "$SANDBOX_USER"
    log_info "User created"
fi

# =============================================================================
# Step 2: Configure subuid/subgid
# =============================================================================

SUBUID_END=$((SUBUID_START + SUBUID_COUNT - 1))

if grep -q "^${SANDBOX_USER}:" /etc/subuid 2>/dev/null; then
    log_warn "subuid entry for '$SANDBOX_USER' already exists"
else
    log_info "Adding subuid range ${SUBUID_START}-${SUBUID_END}..."
    echo "${SANDBOX_USER}:${SUBUID_START}:${SUBUID_COUNT}" >> /etc/subuid
fi

if grep -q "^${SANDBOX_USER}:" /etc/subgid 2>/dev/null; then
    log_warn "subgid entry for '$SANDBOX_USER' already exists"
else
    log_info "Adding subgid range ${SUBUID_START}-${SUBUID_END}..."
    echo "${SANDBOX_USER}:${SUBUID_START}:${SUBUID_COUNT}" >> /etc/subgid
fi

# =============================================================================
# Step 3: Enable lingering
# =============================================================================

log_info "Enabling lingering for '$SANDBOX_USER'..."
loginctl enable-linger "$SANDBOX_USER" 2>/dev/null || {
    # Fallback for systems without loginctl
    mkdir -p /var/lib/systemd/linger
    touch "/var/lib/systemd/linger/${SANDBOX_USER}"
}

# =============================================================================
# Step 4: Firewall rules
# =============================================================================

SANDBOX_UID=$(id -u "$SANDBOX_USER")
log_info "User '$SANDBOX_USER' has UID: $SANDBOX_UID"

# Detect firewall backend
if command -v nft &>/dev/null && systemctl is-active --quiet nftables 2>/dev/null; then
    FIREWALL="nftables"
elif command -v iptables &>/dev/null; then
    FIREWALL="iptables"
else
    log_warn "No supported firewall found (nftables or iptables)"
    FIREWALL="none"
fi

log_info "Detected firewall: $FIREWALL"

case "$FIREWALL" in
    nftables)
        log_info "Configuring nftables rules..."

        # Create nftables config file
        NFT_CONF="/etc/nftables/${SANDBOX_USER}-restrict.nft"
        mkdir -p /etc/nftables

        cat > "$NFT_CONF" << EOF
#!/usr/sbin/nft -f
# Block RFC1918 subnets for ${SANDBOX_USER} user
# Generated by setup-host.sh

table inet ${SANDBOX_USER}_restrict {
    chain output {
        type filter hook output priority 0; policy accept;

        # Block private subnets for ${SANDBOX_USER} (UID ${SANDBOX_UID})
        meta skuid ${SANDBOX_USER} ip daddr 10.0.0.0/8 reject with icmp type admin-prohibited
        meta skuid ${SANDBOX_USER} ip daddr 172.16.0.0/12 reject with icmp type admin-prohibited
        meta skuid ${SANDBOX_USER} ip daddr 192.168.0.0/16 reject with icmp type admin-prohibited
        meta skuid ${SANDBOX_USER} ip daddr 169.254.0.0/16 reject with icmp type admin-prohibited
    }
}
EOF

        # Load the rules
        nft -f "$NFT_CONF"

        # Add include to main nftables.conf if not already present
        if ! grep -q "${SANDBOX_USER}-restrict.nft" /etc/nftables.conf 2>/dev/null; then
            echo "include \"/etc/nftables/${SANDBOX_USER}-restrict.nft\"" >> /etc/nftables.conf
        fi

        log_info "nftables rules configured and will persist across reboots"
        ;;

    iptables)
        log_info "Configuring iptables rules..."

        # Check if rules already exist
        if iptables -C OUTPUT -m owner --uid-owner "$SANDBOX_UID" -d 10.0.0.0/8 -j REJECT 2>/dev/null; then
            log_warn "iptables rules already exist for UID $SANDBOX_UID"
        else
            iptables -A OUTPUT -m owner --uid-owner "$SANDBOX_UID" -d 10.0.0.0/8 -j REJECT
            iptables -A OUTPUT -m owner --uid-owner "$SANDBOX_UID" -d 172.16.0.0/12 -j REJECT
            iptables -A OUTPUT -m owner --uid-owner "$SANDBOX_UID" -d 192.168.0.0/16 -j REJECT
            iptables -A OUTPUT -m owner --uid-owner "$SANDBOX_UID" -d 169.254.0.0/16 -j REJECT

            # Try to persist rules
            if command -v iptables-save &>/dev/null; then
                if [[ -d /etc/iptables ]]; then
                    iptables-save > /etc/iptables/rules.v4
                elif [[ -f /etc/sysconfig/iptables ]]; then
                    iptables-save > /etc/sysconfig/iptables
                else
                    log_warn "Could not persist iptables rules automatically"
                    log_warn "Run 'iptables-save > /path/to/rules' to persist"
                fi
            fi
        fi

        log_info "iptables rules configured"
        ;;

    none)
        log_warn "Skipping firewall configuration"
        log_warn "Manually configure your firewall to block RFC1918 for UID $SANDBOX_UID"
        ;;
esac

# =============================================================================
# Step 5: Verify setup
# =============================================================================

echo ""
echo "=============================================="
echo "Verification"
echo "=============================================="

# Check user
if id "$SANDBOX_USER" &>/dev/null; then
    log_info "User '$SANDBOX_USER' exists (UID: $(id -u $SANDBOX_USER))"
else
    log_error "User '$SANDBOX_USER' not found"
fi

# Check subuid/subgid
if grep -q "^${SANDBOX_USER}:" /etc/subuid; then
    log_info "subuid configured: $(grep "^${SANDBOX_USER}:" /etc/subuid)"
else
    log_error "subuid not configured"
fi

if grep -q "^${SANDBOX_USER}:" /etc/subgid; then
    log_info "subgid configured: $(grep "^${SANDBOX_USER}:" /etc/subgid)"
else
    log_error "subgid not configured"
fi

# Check lingering
if [[ -f "/var/lib/systemd/linger/${SANDBOX_USER}" ]]; then
    log_info "Lingering enabled"
else
    log_warn "Lingering may not be enabled"
fi

# Check podman works
log_info "Testing podman as '$SANDBOX_USER'..."
if sudo -u "$SANDBOX_USER" podman info &>/dev/null; then
    log_info "Podman works as '$SANDBOX_USER'"
else
    log_warn "Podman test failed - may need first-run initialization"
    log_warn "Try: sudo -u $SANDBOX_USER podman info"
fi

echo ""
echo "=============================================="
echo "Setup Complete"
echo "=============================================="
echo ""
echo "Next steps:"
echo "  1. Test podman: sudo -u $SANDBOX_USER podman run --rm alpine echo hello"
echo "  2. Run container: ./run.sh"
echo ""
echo "See docs/SECURITY.md for full documentation."
